title: fh-potsdam
description: fh-potsdam github organisation page
baseurl: /
production_url: http://fh-potsdam.github.io
author: FH-Potsdam InterfaceDesign

# list of repositories that will be hidden from the frontend
repo_blacklist:
  - fh-potsdam.github.com
  - ForschungsFenster-Logger
  - vagrant-package.json

# jekyll settings
exclude: ["README.md"]
auto: true
highlighter: pygments
