title: fh-potsdam
description: fh-potsdam github organisation page
url: http://fh-potsdam.github.io
# baseurl:

author: Interface Design @FHP
author_email: blah@email.test
github: fh-potsdam
# twitter: username
# feedburner: feedname

exclude: ["README.md"]
auto: true
pygments: true
