title: fh-potsdam
description: fh-potsdam github organisation page
baseurl: /
production_url: http://fh-potsdam.github.io

author: FHP InterfaceDesign

exclude: ["README.md"]
auto: true
pygments: true

repo_blacklist:
  - fh-potsdam.github.com
