title: fh-potsdam
description: fh-potsdam github organisation page
baseurl: /
production_url: http://fh-potsdam.github.io
author: FHP InterfaceDesign

# list of repositories that will be hidden from the frontend
repo_blacklist:
  - fh-potsdam.github.com
  - ForschungsFenster-Logger

# jekyll settings
exclude: ["README.md"]
auto: true
pygments: true
