title: fh-potsdam
description: fh-potsdam github organisation page
baseurl: /
production_url: http://fh-potsdam.github.io

author: Interface Design @FHP
# author_email: blah@email.test

exclude: ["README.md"]
auto: true
pygments: true
